/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorCliente;
import ec.ups.edu.controlador.ControladorTicket;
import ec.ups.edu.controlador.ControladorVehiculo;
import ec.ups.edu.dao.ClienteDAO;
import ec.ups.edu.dao.TicketDAO;
import ec.ups.edu.dao.VehiculoDAO;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Adolfo
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private ClienteDAO clienteDAO;
    private VehiculoDAO vehiculoDAO;
    private TicketDAO ticketDAO;

    private ControladorCliente controladorCliente;
    private ControladorVehiculo controladorVehiculo;
    private ControladorTicket controladorTicket;
    
    private VentanaRegistarCliente ventanaRegistrarCliente;
    private VentanaRegistrarVehiculo ventanaRegistrarVehiculo;
    private VentanaRegistrarTicket ventanaRegistrarTicket;
    private VentanaSalidaTicket ventanaSalidaTicket;
    
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        clienteDAO = new ClienteDAO();
        vehiculoDAO = new VehiculoDAO();
        ticketDAO = new TicketDAO();
        
        controladorCliente = new ControladorCliente(clienteDAO, vehiculoDAO);
        controladorVehiculo = new ControladorVehiculo(vehiculoDAO);
        
        ventanaRegistrarCliente = new VentanaRegistarCliente(controladorCliente);
        ventanaRegistrarVehiculo = new VentanaRegistrarVehiculo(controladorCliente, controladorVehiculo
                , ventanaRegistrarCliente);
        ventanaRegistrarTicket = new VentanaRegistrarTicket();
        ventanaSalidaTicket = new VentanaSalidaTicket();
        
        desktopPane.add(ventanaRegistrarCliente);
        desktopPane.add(ventanaRegistrarTicket);
        desktopPane.add(ventanaRegistrarVehiculo);
        desktopPane.add(ventanaSalidaTicket);
        
      /*  localizacion = new Locale("es","EC");
        mensajes = ResourceBundle.getBundle("ec.ups.edu.idiomas.mensajes", localizacion);
        cambiarIdiomas();*/
        
    }
    
    public void cerrarVentanas(){
        ventanaRegistrarCliente.setVisible(false);
        ventanaRegistrarTicket.setVisible(false);
        ventanaRegistrarVehiculo.setVisible(false);
        ventanaSalidaTicket.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuItemRegistrarCliente = new javax.swing.JMenuItem();
        menuItemRegistrarVehiculo = new javax.swing.JMenuItem();
        menuItemEmitirTicket = new javax.swing.JMenuItem();
        menuItemSalidaTicket = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuListar = new javax.swing.JMenu();
        menuItemListarClientes = new javax.swing.JMenuItem();
        menuItemListarVehiculos = new javax.swing.JMenuItem();
        menuItemListarTickets = new javax.swing.JMenuItem();
        menuIdiomas = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Parqueadero");
        setLocation(new java.awt.Point(500, 100));
        setMinimumSize(new java.awt.Dimension(400, 500));

        menuInicio.setMnemonic('f');
        menuInicio.setText("Inicio");

        menuItemRegistrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuItemRegistrarCliente.setMnemonic('o');
        menuItemRegistrarCliente.setText("Registrar cliente");
        menuItemRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarClienteActionPerformed(evt);
            }
        });
        menuInicio.add(menuItemRegistrarCliente);

        menuItemRegistrarVehiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuItemRegistrarVehiculo.setMnemonic('s');
        menuItemRegistrarVehiculo.setText("Registrar vehículo");
        menuInicio.add(menuItemRegistrarVehiculo);

        menuItemEmitirTicket.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuItemEmitirTicket.setMnemonic('a');
        menuItemEmitirTicket.setText("Emitir ticket");
        menuInicio.add(menuItemEmitirTicket);

        menuItemSalidaTicket.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSalidaTicket.setText("Salida ticket");
        menuInicio.add(menuItemSalidaTicket);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuItemExit.setMnemonic('x');
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuInicio.add(menuItemExit);

        menuBar.add(menuInicio);

        menuListar.setMnemonic('e');
        menuListar.setText("Listar");

        menuItemListarClientes.setMnemonic('t');
        menuItemListarClientes.setText("Clientes");
        menuListar.add(menuItemListarClientes);

        menuItemListarVehiculos.setMnemonic('y');
        menuItemListarVehiculos.setText("Vehiculos");
        menuListar.add(menuItemListarVehiculos);

        menuItemListarTickets.setMnemonic('p');
        menuItemListarTickets.setText("Tickets");
        menuListar.add(menuItemListarTickets);

        menuBar.add(menuListar);

        menuIdiomas.setMnemonic('h');
        menuIdiomas.setText("Idiomas");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Español");
        menuIdiomas.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Inglés");
        menuIdiomas.add(aboutMenuItem);

        menuBar.add(menuIdiomas);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarClienteActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        ventanaRegistrarCliente.setVisible(true);
    }//GEN-LAST:event_menuItemRegistrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuIdiomas;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenuItem menuItemEmitirTicket;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemListarClientes;
    private javax.swing.JMenuItem menuItemListarTickets;
    private javax.swing.JMenuItem menuItemListarVehiculos;
    private javax.swing.JMenuItem menuItemRegistrarCliente;
    private javax.swing.JMenuItem menuItemRegistrarVehiculo;
    private javax.swing.JMenuItem menuItemSalidaTicket;
    private javax.swing.JMenu menuListar;
    // End of variables declaration//GEN-END:variables

}
